// Login types
export const LOGINREQUEST = 'LOGIN_REQUEST';
export const LOGINSUCCESS = 'LOGIN_SUCCESS';
export const LOGINFAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CHECKAUTH = 'CHECK_AUTH';

// Missions types
export const GET_MISSIONS_LIST_REQUEST = 'GET_MISSIONS_LIST_REQUEST';
export const GET_MISSIONS_LIST_SUCCESS = 'GET_MISSIONS_LIST_SUCCESS';
export const GET_MISSIONS_LIST_FAILED = 'GET_MISSIONS_LIST_FAILED';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE'
// Cadres types
export const GET_CADRES_REQUEST = 'GET_CADRES_REQUEST';
export const GET_CADRES_SUCCESS = 'GET_CADRES_SUCCESS';
export const GET_CADRES_FAILED = 'GET_CADRES_FAILED';

// Cars types
export const GET_CARS_REQUEST = 'GET_CADRES_REQUEST';
export const GET_CARS_SUCCESS = 'GET_CADRES_SUCCESS';
export const GET_CARS_FAILED = 'GET_CADRES_FAILED' ;

