// Login types
export const LOGINREQUEST = 'LOGIN_REQUEST';
export const LOGINSUCCESS = 'LOGIN_SUCCESS';
export const LOGINFAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CHECKAUTH = 'CHECK_AUTH';


export const CREATE_ORDERMISSION_REQUEST = 'CREATE_ORDERMISSION_REQUEST';
export const CREATE_ORDERMISSION_SUCCESS = 'CREATE_ORDERMISSION_SUCCESS';
export const CREATE_ORDERMISSION_FAILURE = 'CREATE_ORDERMISSION_FAILURE';
export const UPDATE_ORDERMISSION_REQUEST = 'UPDATE_ORDERMISSION_REQUEST';
export const UPDATE_ORDERMISSION_SUCCESS = 'UPDATE_ORDERMISSION_SUCCESS';
export const UPDATE_ORDERMISSION_FAILURE = 'UPDATE_ORDERMISSION_FAILURE';
export const DELETE_ORDERMISSION_REQUEST = 'DELETE_ORDERMISSION_REQUEST';
export const DELETE_ORDERMISSION_SUCCESS = 'DELETE_ORDERMISSION_SUCCESS';
export const DELETE_ORDERMISSION_FAILURE = 'DELETE_ORDERMISSION_FAILURE';
export const FETCH_ORDERMISSIONS_REQUEST = "FETCH_ORDERMISSIONS_REQUEST";
export const FETCH_ORDERMISSIONS_SUCCESS = "FETCH_ORDERMISSIONS_SUCCESS";
export const FETCH_ORDERMISSIONS_FAILURE = "FETCH_ORDERMISSIONS_FAILURE";
export const UPDATESTATUS_ORDERMISSION_REQUEST = "UPDATESTATUS_ORDERMISSION_REQUEST";
export const UPDATESTATUS_ORDERMISSION_SUCCESS = "UPDATESTATUS_ORDERMISSION_SUCCESS";
export const UPDATESTATUS_ORDERMISSION_FAILURE = "UPDATESTATUS_ORDERMISSION_FAILURE";



export const FETCH_ENTERPRISE_ID_REQUEST = 'FETCH_ENTERPRISE_ID_REQUEST';
export const FETCH_ENTERPRISE_ID_SUCCESS = 'FETCH_ENTERPRISE_ID_SUCCESS';
export const FETCH_ENTERPRISE_ID_FAILURE = 'FETCH_ENTERPRISE_ID_FAILURE';
export const FETCH_ENTERPRISES_REQUEST = 'FETCH_ENTERPRISES_REQUEST';
export const FETCH_ENTERPRISES_SUCCESS = 'FETCH_ENTERPRISES_SUCCESS';
export const FETCH_ENTERPRISES_FAILURE = 'FETCH_ENTERPRISES_FAILURE';
export const ADD_ENTERPRISE_REQUEST = 'ADD_ENTERPRISE_REQUEST';
export const ADD_ENTERPRISE_SUCCESS = 'ADD_ENTERPRISE_SUCCESS';
export const ADD_ENTERPRISE_FAILURE = 'ADD_ENTERPRISE_FAILURE';
export const UPDATE_ENTERPRISE_REQUEST = 'UPDATE_ENTERPRISE_REQUEST';
export const UPDATE_ENTERPRISE_SUCCESS = 'UPDATE_ENTERPRISE_SUCCESS';
export const UPDATE_ENTERPRISE_FAILURE = 'UPDATE_ENTERPRISE_FAILURE';

// Control Type 31
export const CREATE_CONTROL_31_REQUEST = 'CREATE_CONTROL_31_REQUEST';
export const CREATE_CONTROL_31_SUCCESS = 'CREATE_CONTROL_31_SUCCESS';
export const CREATE_CONTROL_31_FAILURE = 'CREATE_CONTROL_31_FAILURE';
export const UPDATE_CONTROL_31_REQUEST = 'UPDATE_CONTROL_31_REQUEST';
export const UPDATE_CONTROL_31_SUCCESS = 'UPDATE_CONTROL_31_SUCCESS';
export const UPDATE_CONTROL_31_FAILURE = 'UPDATE_CONTROL_31_FAILURE';
export const DELETE_CONTROL_31_REQUEST = 'DELETE_CONTROL_31_REQUEST';
export const DELETE_CONTROL_31_SUCCESS = 'DELETE_CONTROL_31_SUCCESS';
export const DELETE_CONTROL_31_FAILURE = 'DELETE_CONTROL_31_FAILURE';
export const FETCH_CONTROLS_31_REQUEST = "FETCH_CONTROLS_31_REQUEST";
export const FETCH_CONTROLS_31_SUCCESS = "FETCH_CONTROLS_31_SUCCESS";
export const FETCH_CONTROLS_31_FAILURE = "FETCH_CONTROLS_31_FAILURE";

// Control Type 24
export const CREATE_CONTROL_24_REQUEST = 'CREATE_CONTROL_24_REQUEST';
export const CREATE_CONTROL_24_SUCCESS = 'CREATE_CONTROL_24_SUCCESS';
export const CREATE_CONTROL_24_FAILURE = 'CREATE_CONTROL_24_FAILURE';
export const UPDATE_CONTROL_24_REQUEST = 'UPDATE_CONTROL_24_REQUEST';
export const UPDATE_CONTROL_24_SUCCESS = 'UPDATE_CONTROL_24_SUCCESS';
export const UPDATE_CONTROL_24_FAILURE = 'UPDATE_CONTROL_24_FAILURE';
export const DELETE_CONTROL_24_REQUEST = 'DELETE_CONTROL_24_REQUEST';
export const DELETE_CONTROL_24_SUCCESS = 'DELETE_CONTROL_24_SUCCESS';
export const DELETE_CONTROL_24_FAILURE = 'DELETE_CONTROL_24_FAILURE';
export const FETCH_CONTROLS_24_REQUEST = "FETCH_CONTROLS_24_REQUEST";
export const FETCH_CONTROLS_24_SUCCESS = "FETCH_CONTROLS_24_SUCCESS";
export const FETCH_CONTROLS_24_FAILURE = "FETCH_CONTROLS_24_FAILURE";
export const FETCH_CONTROL_24_BY_ID_REQUEST = "FETCH_CONTROL_24_BY_ID_REQUEST"
export const FETCH_CONTROL_24_BY_ID_SUCCESS = "FETCH_CONTROL_24_BY_ID_SUCCESS"
export const FETCH_CONTROL_24_BY_ID_FAILURE = "FETCH_CONTROL_24_BY_ID_FAILURE"

export const FETCH_STATISTICS_REQUEST = 'FETCH_STATISTICS_REQUEST';
export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_STATISTICS_FAILURE = 'FETCH_STATISTICS_FAILURE';

export const FETCH_OBJECT_REQUEST = 'FETCH_OBJECT_REQUEST';
export const FETCH_OBJECT_SUCCESS = 'FETCH_OBJECT_SUCCESS';
export const FETCH_OBJECT_FAILURE = 'FETCH_OBJECT_FAILURE';

export const FETCH_POINTVENTE_ID_REQUEST = "FETCH_POINTVENTE_ID_REQUEST";
export const FETCH_POINTVENTE_ID_SUCCESS = "FETCH_POINTVENTE_ID_SUCCESS";
export const FETCH_POINTVENTE_ID_FAILURE = "FETCH_POINTVENTE_ID_FAILURE";
export const FETCH_POINTVENTES_REQUEST = "FETCH_POINTVENTES_REQUEST";
export const FETCH_POINTVENTES_SUCCESS = "FETCH_POINTVENTES_SUCCESS";
export const FETCH_POINTVENTES_FAILURE = "FETCH_POINTVENTES_FAILURE";
export const ADD_POINTVENTE_REQUEST = "ADD_POINTVENTE_REQUEST";
export const ADD_POINTVENTE_SUCCESS = "ADD_POINTVENTE_SUCCESS";
export const ADD_POINTVENTE_FAILURE = "ADD_POINTVENTE_FAILURE";
export const UPDATE_POINTVENTE_REQUEST = "UPDATE_POINTVENTE_REQUEST";
export const UPDATE_POINTVENTE_SUCCESS = "UPDATE_POINTVENTE_SUCCESS";
export const UPDATE_POINTVENTE_FAILURE = "UPDATE_POINTVENTE_FAILURE";

// INDH action types
export const FETCH_INDH_ID_REQUEST = 'FETCH_INDH_ID_REQUEST';
export const FETCH_INDH_ID_SUCCESS = 'FETCH_INDH_ID_SUCCESS';
export const FETCH_INDH_ID_FAILURE = 'FETCH_INDH_ID_FAILURE';
export const FETCH_INDHS_REQUEST = 'FETCH_INDHS_REQUEST';
export const FETCH_INDHS_SUCCESS = 'FETCH_INDHS_SUCCESS';
export const FETCH_INDHS_FAILURE = 'FETCH_INDHS_FAILURE';
export const SEARCH_INDH_REQUEST = 'SEARCH_INDH_REQUEST';
export const SEARCH_INDH_SUCCESS = 'SEARCH_INDH_SUCCESS';
export const SEARCH_INDH_FAILURE = 'SEARCH_INDH_FAILURE';
export const ADD_INDH_REQUEST = 'ADD_INDH_REQUEST';
export const ADD_INDH_SUCCESS = 'ADD_INDH_SUCCESS';
export const ADD_INDH_FAILURE = 'ADD_INDH_FAILURE';
export const UPDATE_INDH_REQUEST = 'UPDATE_INDH_REQUEST';
export const UPDATE_INDH_SUCCESS = 'UPDATE_INDH_SUCCESS';
export const UPDATE_INDH_FAILURE = 'UPDATE_INDH_FAILURE';
export const DELETE_INDH_REQUEST = 'DELETE_INDH_REQUEST';
export const DELETE_INDH_SUCCESS = 'DELETE_INDH_SUCCESS';
export const DELETE_INDH_FAILURE = 'DELETE_INDH_FAILURE';
export const FETCH_INDH_HISTORIQUE_REQUEST = 'FETCH_INDH_HISTORIQUE_REQUEST';
export const FETCH_INDH_HISTORIQUE_SUCCESS = 'FETCH_INDH_HISTORIQUE_SUCCESS';
export const FETCH_INDH_HISTORIQUE_FAILURE = 'FETCH_INDH_HISTORIQUE_FAILURE';
export const UPDATE_INDH_OBSERVATION_REQUEST = 'UPDATE_INDH_OBSERVATION_REQUEST';
export const UPDATE_INDH_OBSERVATION_SUCCESS = 'UPDATE_INDH_OBSERVATION_SUCCESS';
export const UPDATE_INDH_OBSERVATION_FAILURE = 'UPDATE_INDH_OBSERVATION_FAILURE';